// Generated by CoffeeScript 2.5.1
import { desc, run, task } from "https://deno.land/x/drake@v1.4.5/mod.ts";
desc("Minimal Drake task");
task("hello", [], () => {
  return console.log("Hello World!");
});
run();