// Generated by CoffeeScript 2.5.1
// Output: JSON Data
var error, json, text;
json = fetch('https://api.github.com/users/denoland');
json.then(response => {
  return response.json();
}).then(jsonData => {
  return console.log(jsonData);
}); // Output: HTML Data

text = fetch('https://deno.land/');
text.then(response => {
  return response.text();
}).then(textData => {
  return console.log(textData);
}); // Output: Error Message

error = fetch('https://does.not.exist/');
error.catch(error => {
  return console.log(error.message);
});