// Generated by CoffeeScript 2.5.1
var text, writeJson;
text = Deno.readTextFile('./example/js/04_people.json');
text.then(response => {
  return console.log(response);
});

writeJson = (path, data) => {
  try {
    Deno.writeTextFileSync(path, JSON.stringify(data));
    return "Written to " + path;
  } catch (error) {
    return e => {
      return e.message;
    };
  }
};

console.log(writeJson("./example/js/04_people.json", {
  hello: "World"
}));