// Generated by CoffeeScript 2.5.1
var conn, listener;
listener = Deno.listen({
  port: 8080
});
console.log("listening on 0.0.0.0:8080"); //@for-await-of

for (conn in listener) {
  Deno.copy(conn, conn);
}