// Generated by CoffeeScript 2.5.1
var capitalize, hello;

capitalize = word => {
  return word.charAt(0).toUpperCase() + word.slice(1);
};

hello = name => {
  return "Hello " + capitalize(name);
};

console.log(hello("john"));
console.log(hello("Sarah"));
console.log(hello("kai"));